export const TOPIC_MONTH_MAPPING: Record<string, number> = {
  "Acids and Bases": 8,
  "Acids, Bases and Salts": 8,
  "Active & Passive Voice": 8,
  "Antonyms": 2,
  "Articles": 7,
  "Carbon and its Compounds": 2,
  "Chemical Reactions and Equations": 7,
  "Chemical Reactions & Gas Evolution": 7,
  "Circulation": 7,
  "Class 10 English Prose Literature": 9,
  "Classification of Elements": 12,
  "Climate of India": 7,
  "Conditional Clauses (Type 3)": 10,
  "Conjunctions": 8,
  "Constitution of India": 12,
  "Control and Coordination": 10,
  "Coordinate Geometry": 10,
  "Coordination": 10,
  "Coordination in Plants": 10,
  "Degrees of Comparison": 11,
  "Democracy & Elections": 1,
  "Democratic Politics & Parliament": 8,
  "Development & Economic Classification": 1,
  "Development & Economics": 9,
  "Direct & Indirect Speech": 9,
  "Drainage & Rivers": 8,
  "Economy": 2,
  "Electric Current": 12,
  "Electric Current & Circuits": 12,
  "Electromagnetism": 1,
  "Employment Programs": 3,
  "Employment & Sectors": 6,
  "English Literature Reader": 11,
  "English Reader Literature": 11,
  "Environmental Movements": 1,
  "Excretion": 9,
  "Excretion - Renal System": 9,
  "Figures of Speech": 9,
  "Food Security in India": 8,
  "Fundamental Rights & Writs": 12,
  "Future Perfect Tense": 6,
  "Geometry - Circles": 2,
  "Global Economic Institutions": 2,
  "Globalisation & World Trade": 1,
  "Heredity": 12,
  "Heredity and Evolution": 12,
  "Heredity & Genetics": 12,
  "Human Eye & Refraction": 9,
  "Idioms": 12,
  "Idioms and Phrases": 12,
  "Idioms & Proverbs": 12,
  "Indian Constitution": 12,
  "Indian Constitution & Rights": 12,
  "Indian Democracy & Elections": 1,
  "India - Relief Features": 9,
  "India Relief Features": 6,
  "India: Relief Features (Map Skills)": 11,
  "India Relief & Location": 6,
  "Linear Equations": 8,
  "Linear Equations in Two Variables": 8,
  "Logarithms": 6,
  "Logarithms & Real Numbers": 6,
  "Making of Independent India": 1,
  "Mensuration": 11,
  "Modal Auxiliaries": 1,
  "Money & Credit": 10,
  "National Movement": 11,
  "National Movement - Civil Disobedience": 11,
  "Nutrition & Digestion": 6,
  "Nutrition - Human Digestion": 6,
  "Nutrition - Photosynthesis": 6,
  "Nutrition & Vitamins": 6,
  "One-word Substitutes": 6,
  "One Word Substitutes": 6,
  "Our Environment": 1,
  "Our Environment - Ecosystems": 1,
  "Parts of Speech": 6,
  "Past Perfect Tense": 2,
  "Periodic Classification": 11,
  "Personality Development Literature": 10,
  "Photosynthesis": 10,
  "Phrasal Verbs": 1,
  "Physiographic Divisions (Map Skills)": 12,
  "Physiography": 8,
  "Polynomials": 7,
  "Population": 9,
  "Population & Demographics": 9,
  "Population & Human Resources": 9,
  "Population & Literacy": 9,
  "Post-Independence India": 9,
  "Preamble & Indian Constitution": 12,
  "Prefixes & Antonyms": 3,
  "Prepositions": 7,
  "Principles of Metallurgy": 2,
  "Probability": 1,
  "Progressions": 9,
  "Progressions (AP & GP)": 9,
  "Punctuation": 2,
  "Quadratic Equations": 9,
  "Question Tags": 9,
  "Real Numbers": 6,
  "Real Numbers - Fundamental Theorem of Arithmetic": 6,
  "Reflection of Light": 6,
  "Refraction & Lenses": 9,
  "Refraction & Mirrors (Ray Diagram)": 9,
  "Refraction of Light": 9,
  "Reproduction": 11,
  "Respiration": 7,
  "Respiration - Fermentation": 7,
  "Rivers & Geography": 8,
  "Rivers & Multipurpose Projects": 8,
  "Rivers & Water Resources": 8,
  "Rivers & Water Systems": 8,
  "Salts & Chemistry": 1,
  "Sectors of Economy (Information Skills)": 2,
  "Sectors of the Indian Economy": 2,
  "Sets": 7,
  "Similar Triangles": 10,
  "Simple, Compound & Complex Sentences": 12,
  "Social Movements & Civic Rights": 7,
  "Spelling": 2,
  "Spelling Accuracy": 1,
  "Spotting Errors": 11,
  "Statistics": 2,
  "Structure of Atom": 11,
  "Structure of Atom & Periodic Table": 11,
  "Subject-Verb Agreement": 8,
  "Sustainable Development": 9,
  "Synonyms": 2,
  "Tenses & Prepositions": 6,
  "The World Between Wars": 10,
  "The World Between Wars & Post-War World": 10,
  "The World Between Wars - Russian Revolution": 10,
  "The World Between Wars (World Map Skills)": 10,
  "Transportation": 8,
  "Transportation - Blood Pressure": 8,
  "Transportation & Heart": 8,
  "Transportation in Plants": 8,
  "Triangles & Pythagoras": 10,
  "Trigonometric Identities": 10,
  "Trigonometric Values": 6,
  "Trigonometry": 12,
  "Vocabulary & Antonyms": 7,
  "Water Resources": 11,
  "World Wars": 6,
  "उपसर्ग": 2,
  "उपसर्ग एवं प्रत्यय": 2,
  "कवि परिचय": 3,
  "कारक": 10,
  "कारक (Case)": 7,
  "काल": 11,
  "काल (Tense)": 11,
  "क्रिया": 12,
  "क्रिया एवं वाक्य": 12,
  "तत्सम एवं तद्भव": 11,
  "दीर्घ संधि": 9,
  "पर्यायवाची": 12,
  "पर्यायवाची शब्द": 12,
  "पाठ्य पुस्तक": 8,
  "पाठ्य पुस्तक / विधा": 3,
  "पाठ्य पुस्तक / संदेश": 6,
  "प्रत्यय": 1,
  "मुहावरे": 10,
  "मुहावरे (Idioms)": 10,
  "लिंग": 10,
  "लेखक परिचय": 6,
  "वर्तनी शुद्धि": 9,
  "वाक्य के भेद": 8,
  "विलोम शब्द": 6,
  "व्यंजन संधि": 9,
  "व्याकरण": 1,
  "संज्ञा": 6,
  "संधि": 9,
  "संधि (Sandhi)": 9,
  "संधि विच्छेद": 9,
  "समास": 8,
  "समास (Samas)": 8,
  "समास विग्रह": 8,
  "साहित्य": 1,
  "साहित्यिक परिचय": 11,
  "అర్థాలు & పర్యాయాలు": 3,
  "అలంకారాలు": 8,
  "ఉపజాతి పద్య ఛందస్సు": 9,
  "ఉపమాలంకారం": 6,
  "కర్తరి - కర్మణి వాక్యాలు": 12,
  "కవుల పరిచయం": 6,
  "కవుల పరిచయం / ఆధునిక కవిత్వం": 6,
  "కవుల పరిచయం / పాఠ్యభాగం": 6,
  "కవుల పరిచయం / శతక సాహిత్యం": 6,
  "కాలాలు & క్రియలు": 12,
  "గేయ సాహిత్యం & కవులు": 6,
  "ఛందస్సు": 9,
  "జాతి పద్య ఛందస్సు": 9,
  "జాతీయాలు": 10,
  "పర్యాయపదాలు": 7,
  "పాఠ్యభాగ విషయ సంగ్రహం": 7,
  "పాఠ్యభాగ సందేశం": 11,
  "ప్రకృతి - వికృతి": 12,
  "వాక్య రకాలు": 12,
  "వాక్య విశ్లేషణ (కర్త, కర్మ, క్రియ)": 12,
  "వ్యతిరేకార్థక వాక్యాలు": 12,
  "శతక సాహిత్యం": 8,
  "సంధులు": 6,
  "సమాసాలు": 7,
  "సవర్ణదీర్ఘ సంధి": 11,
  "సామెతలు": 11,
  "సాహిత్య పరిచయం": 10
};

/**
 * Returns true if the given topic is scheduled to be completed by the target month.
 * Academic year starts in June (6).
 */
export function isTopicEligible(topic: string, currentMonth: number): boolean {
  const scheduledMonth = TOPIC_MONTH_MAPPING[topic];
  if (!scheduledMonth) return true; // Fallback to allow if unknown

  const academicOrder = [6, 7, 8, 9, 10, 11, 12, 1, 2, 3, 4, 5];
  const currentIndex = academicOrder.indexOf(currentMonth);
  const scheduledIndex = academicOrder.indexOf(scheduledMonth);
  
  if (currentIndex === -1 || scheduledIndex === -1) return true;
  return scheduledIndex <= currentIndex;
}

export function getCurrentSystemMonth(): number {
  return new Date().getMonth() + 1; // 1-12
}
